---
title: "Project1"
author: "Vito Frank Leonardo"
date: "6/14/2021"
output: 
  html_document:
    toc: yes
    toc_float: no
    toc_depth: 3
---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Packages Needed:
```{r}
library(tidyverse)
library(httr)
library(jsonlite)
library(gtools)
```


# Functions to query the data
```{r BaseURL}
Base_URL <- "https://records.nhl.com/site/api"
```


```{r Franchise}
FranchiseInfo <- function(ID=NULL, Name=NULL){
  franchise <- "/franchise"
  req <- GET(paste0(Base_URL,franchise)) # from httr library
  data <- content(req) # from httr library

  df <- data.frame(matrix(rep(0,8), nrow=1))
  colnames(df) <- names(data$data[[2]])
  for( i in 1:length(data$data)){
    datalist <- data$data[[i]]
    temp <- data.frame(matrix(datalist, nrow=1))
    df[i,] <- temp
  }

  if(is.null(ID) & is.null(Name)){
    return(df)
  } else{
      NamesDf <- df %>% 
       select(id, teamCommonName) %>%
       filter(teamCommonName %in% Name)
      ID <- unique(union(ID,unlist(NamesDf$id )))
  
    return(df %>% filter(id %in% ID))
  }
}
```  


```{r teamTotals}

TeamTotals <- function(ID=NULL, Name=NULL){

  NamesDf <- FranchiseInfo(ID,Name) %>% 
    select(id, fullName, teamCommonName, teamPlaceName, teamAbbrev) %>%
    rename(franchiseId = id)
  
  teamTotals <- "/franchise-team-totals"
  req <- GET(paste0(Base_URL,teamTotals)) # from httr library
  data <- (content(req)) # from httr library

  df <- data.frame(matrix(rep(0,length(data$data[[1]])), nrow=1))
  colnames(df) <- names(data$data[[2]])
  for( i in 1:length(data$data)){
    datalist <- data$data[[i]]
    temp <- data.frame(matrix(datalist, nrow=1))
    df[i,] <- temp
  }
  
  df <- df %>% left_join(NamesDf,"franchiseId")
  
  if(is.null(ID) & is.null(Name)){
    return(df)
  } else{
      NamesDf <- df %>% 
       select(id, teamCommonName) %>%
       filter(teamCommonName %in% Name)
      ID <- unique(union(ID,unlist(NamesDf$id )))
  
    return(df %>% filter(id %in% ID))
  }
}

  
```
 
```{r}
AssistingFun <- function(Type,ID){

  Records <- paste0("/franchise-",Type,"-records?cayenneExp=franchiseId=",ID[1])
  req <- GET(paste0(Base_URL,Records)) # from httr library
  data <- content(req) # from httr library
  df <- data.frame(matrix(data$data[[1]],nrow = 1))
  colnames(df) <- names(data$data[[1]])
  
  if(length(ID)!=1){
    for(i in 2:length(ID)){
    Records <- paste0("/franchise-",Type,"-records?cayenneExp=franchiseId=",ID[i])
    req <- GET(paste0(Base_URL,Records)) # from httr library
    data <- content(req) # from httr library
    temp <- data.frame(matrix(data$data[[1]],nrow = 1))
    colnames(temp) <- names(df)
    df <- rbind(df,temp)
    }
  }

  return(df)
}  

``` 
 
```{r Season}

SeasonRecords <- function(ID =NULL, Name = NULL){

  NamesDf <- FranchiseInfo(ID,Name) 
  ID <- unlist(NamesDf$id )
  Type = "season"

  AssistingFun(Type,ID)
}
```



```{r}

GoalieRecords <- function(ID =NULL, Name = NULL){
  
  NamesDf <- FranchiseInfo(ID,Name) 
  ID <- unlist(NamesDf$id )
  ID <- ID[!ID == 39]
  Type <- "goalie"
  
  AssistingFun(Type,ID)
}
```

```{r}

SkaterRecords <- function(ID =NULL, Name = NULL){

  NamesDf <- FranchiseInfo(ID,Name) 
  ID <- unlist(NamesDf$id )
  ID <- ID[!ID == 39]
  Type = "skater"

  Records <- paste0("/franchise-",Type,"-records?cayenneExp=franchiseId=",ID[1])
  req <- GET(paste0(Base_URL,Records)) # from httr library
  data <- content(req) # from httr library
  df <- data.frame(matrix(data$data[[1]],nrow = 1))
  colnames(df) <- names(data$data[[1]])
  for(j in 2:length(data$data)){
    temp <- data.frame(matrix(data$data[[j]],nrow = 1))
    colnames(temp) <- colnames(df)
    df <- rbind(df,temp)
  }
  if(length(ID)!= 1){
    for(i in 2:length(ID)){
    Records <- paste0("/franchise-",Type,"-records?cayenneExp=franchiseId=",ID[i])
    req <- GET(paste0(Base_URL,Records)) # from httr library
    data <- content(req) # from httr library
      for(j in 1:length(data$data)){
      temp <- data.frame(matrix(data$data[[j]],nrow = 1))
      colnames(temp) <- colnames(df)
      df <- rbind(df,temp)
      }
    }
  }

  return(df)

}
```



```{r}

AdminRecords <- function(ID =NULL, Name = NULL){
  
  NamesDf <- FranchiseInfo(ID,Name) 
  ID <- unlist(NamesDf$id )
  ID <- ID[!ID == 39]
  df<-NULL
  
  Records <- paste0("/franchise-detail?cayenneExp=mostRecentTeamId=",ID[1])
  req <- GET(paste0(Base_URL,Records)) # from httr library
  data <- content(req) # from httr library
  if(!is.null(unlist(data$data))){
    df <- data.frame(matrix(data$data[[1]],nrow = 1))
    colnames(df) <- names(data$data[[1]])
  }
  
  if(length(ID)!=1){
    for(i in 2:length(ID)){
    Records <- paste0("/franchise-detail?cayenneExp=mostRecentTeamId=",ID[i])
    req <- GET(paste0(Base_URL,Records)) # from httr library
    data <- content(req) # from httr library
      if(!is.null(unlist(data$data))){
        temp <- data.frame(matrix(data$data[[1]],nrow = 1))
        colnames(temp) <- names(df)
        df <- rbind(df,temp) 
      }
    }
  }
  if(is.null(df)){
    stop("There is no data for the ID specified")
  }
  return(df)
}

```

```{r}

StatsExpandMod <- function(ID=NULL,Name=NULL){
  Base_URL_Stats <- "https://statsapi.web.nhl.com/api/v1/teams/"
  Modifier <- "?expand=team.stats"
  
  NamesDf <- FranchiseInfo(ID,Name) 
  ID <- unlist(NamesDf$id )
  ID <- ID[!ID == 39]
  df<-NULL
  
  
  req <- GET(paste0(Base_URL_Stats,1,Modifier)) # from httr library
  data <- content(req) # from httr library
  df <- data.frame(data$teams[[1]])
  for(i in 2:38){
    req <- GET(paste0(Base_URL_Stats,i,Modifier)) # from httr library
    data <- content(req) # from httr library
    temp <- data.frame(data$teams[[1]])
    df <- smartbind(df,temp)
    }    
  if(!is.null(ID)){
    return(df %>% filter(franchise.franchiseId %in% ID))
  } else return(df)
}

```

## Wrapper Function
```{r Wrapper}
Wrapper <- function(fun,ID=NULL,Name=NULL){
  switch(fun,
             Info = FranchiseInfo(ID,Name),
             Totals = TeamTotals(ID,Name),
             Goalie = GoalieRecords(ID,Name), 
             Season = SeasonRecords(ID,Name), 
             Skater = SkaterRecords(ID,Name), 
             Admin= AdminRecords(ID,Name), 
             TeamStat = StatsExpandMod(ID,Name),
             stop("fun must be one of the following: Info, Totals, Goalie, Season, Skater, Admin or TeamStat. fun must also be in quotation marks"))
  
}
```

# Exploratory Data Analysis 
```{r}
NY.Info <-Wrapper("Info", Name = c("Islanders", "Rangers", "Sabres"))
NY.Teams <- c("Islanders", "Rangers", "Sabres")
NY.Season <- Wrapper("Season", Name = NY.Teams)
NY.Skater <- Wrapper("Skater",  Name = NY.Teams)
NY.TeamStat<- Wrapper("TeamStat",Name = NY.Teams)

table(unlist(NY.Skater$franchiseName))
table(unlist(NY.Skater$franchiseName),unlist(NY.Skater$activePlayer))
table(unlist(NY.Skater$franchiseName),unlist(NY.Skater$seasons))


NY.Skater %>% 
  mutate(franchiseName = factor(unlist(franchiseName)),
         activePlayer = factor(unlist(activePlayer))) %>%
  group_by(franchiseName, activePlayer) %>%
  summarise(avgGames = mean(as.numeric(gamesPlayed)), 
            medGames = median(as.numeric(gamesPlayed)), 
            varGames = var(as.numeric(gamesPlayed)) )

NY.Skater %>% 
  mutate(franchiseName = factor(unlist(franchiseName)),
         activePlayer = factor(unlist(activePlayer))) %>%
  group_by(franchiseName, activePlayer) %>%
  summarise(avgGoals = mean(as.numeric(goals)), 
            medGoals = median(as.numeric(goals)), 
            varGoals = var(as.numeric(goals)) )

NY.Skater %>% 
  mutate(franchiseName = factor(unlist(franchiseName)),
         activePlayer = factor(unlist(activePlayer))) %>%
  group_by(franchiseName, activePlayer) %>%
  summarise(avgAssists = mean(as.numeric(assists)), 
            medAssists = median(as.numeric(assists)), 
            varAssists = var(as.numeric(assists)) )

NY.Skater %>% 
  filter(seasons > 3) %>%
  mutate(franchiseName = factor(unlist(franchiseName)),
         activePlayer = factor(unlist(activePlayer))) %>%
  group_by(franchiseName, activePlayer) %>%
  summarise(avgGoals = mean(as.numeric(goals)), 
            medGoals = median(as.numeric(goals)), 
            varGoals = var(as.numeric(goals)) )

NY.Skater %>% 
  filter(seasons > 3) %>%
  mutate(franchiseName = factor(unlist(franchiseName)),
         activePlayer = factor(unlist(activePlayer))) %>%
  group_by(franchiseName, activePlayer) %>%
  summarise(avgAssists = mean(as.numeric(assists)), 
            medAssists = median(as.numeric(assists)), 
            varAssists = var(as.numeric(assists)) )

NY.Skater.edit <- NY.Skater %>% 
  filter(seasons > 3) %>%
  mutate(NYteams = factor(unlist(franchiseName)),
         activePlayer = factor(unlist(activePlayer)), 
         assists = as.numeric(assists),
         goals = as.numeric(goals), 
         gamesPlayed = as.numeric(gamesPlayed),
         GoalsPerGame = goals/gamesPlayed,
         AssistsPerGame = assists/gamesPlayed) 

ggplot(data = NY.Skater.edit, mapping = aes(x=NYteams, y=goals))+
  geom_boxplot() +
  geom_jitter(aes(color = NYteams))+
  labs(x = "NY Teams")

ggplot(data = NY.Skater.edit, mapping = aes(x=NYteams, y=assists))+
  geom_boxplot() +
  geom_jitter(aes(color = NYteams))+
  labs(x = "NY Teams")
# Historically the teams seem to be the same

ggplot(data = NY.Skater.edit,
       mapping = aes(x=goals, fill = NYteams))+
  geom_histogram() +
  facet_grid(col = vars(NYteams))

ggplot(data = NY.Skater.edit, 
       mapping = aes(x=GoalsPerGame, 
                     y = AssistsPerGame, 
                     group = NYteams, 
                     color = NYteams)) +
  geom_point() +
  geom_smooth(method = lm, aes(color = NYteams)) 
  

BestScorers <- NY.Skater %>% 
  mutate(NYteams = factor(unlist(franchiseName)),
         activePlayer = factor(unlist(activePlayer))) %>%
  group_by(NYteams, activePlayer) %>%
  summarise(maxGoals = max(as.numeric(goals)) )


ggplot(BestScorers, aes(x=NYteams,fill = activePlayer)) +
  geom_bar(aes(y=maxGoals),position = "dodge", stat = "identity")
# Islanders have the best scorer in NY history and currently have the best active scorer

NY.TeamStat.edit <- NY.TeamStat %>% 
  select(name, teamStats.splits.stat.goalsPerGame, teamStats.splits.stat.shotsPerGame) %>%
  rename(GoalsPerGame = teamStats.splits.stat.goalsPerGame, 
         ShotsPerGame = teamStats.splits.stat.shotsPerGame) %>%
  mutate(ScorePerc = GoalsPerGame/ShotsPerGame) %>%
  gather(key = Variable, value = value, 2:3)
print(NY.TeamStat.edit)

ggplot(NY.TeamStat.edit, mapping = aes(x=factor(name), fill = Variable))+
    geom_bar(aes(y=value),position = "dodge", stat = "identity")

ggplot(NY.TeamStat.edit, mapping = aes(x=factor(name)))+
  geom_bar(aes(y=ScorePerc/2, fill = factor(name)), stat = "identity")

```


